"""Images added

Revision ID: 8be3e693f23f
Revises: ffc54402a8e8
Create Date: 2024-02-11 16:10:53.211841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8be3e693f23f'
down_revision = 'ffc54402a8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('goods', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('image', mysql.VARCHAR(length=2048), nullable=True))
    op.drop_table('images')
    # ### end Alembic commands ###
