"""Categories and brands added

Revision ID: ffc54402a8e8
Revises: 2c8089ca6c75
Create Date: 2024-02-07 19:09:22.207199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc54402a8e8'
down_revision = '2c8089ca6c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('goods', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('goods', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goods', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'goods', 'brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.drop_constraint(None, 'goods', type_='foreignkey')
    op.drop_column('goods', 'category_id')
    op.drop_column('goods', 'brand_id')
    op.drop_table('categories')
    op.drop_table('brands')
    # ### end Alembic commands ###
